import { Book } from './book';

export const BOOKS: Book[] = [
    {   id: 1,
        title: "Harry Potter and the Sorcerer's Stone",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 10
         },
    {   id: 2,
        title: "Harry Potter and the Chamber of Secrets",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 7
         },
    {   id: 3,
        title: "Harry Potter and the Prisoner of Azkaban",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 10
         },
    {   id: 4,
        title: "Harry Potter and the Goblet of Fire",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 7
         },
    {  id: 5,
        title: "Harry Potter and the Order of the Phoenix",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 9
          },
    {   id: 6,
        title: "Harry Potter and the Half-Blood Prince",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 9
         },
    {   id: 7,
        title: "Harry Potter and the Deathly Hallows",
        read: true,
        ownership: true,
        female_protagonist: false,
        female_role_model: true,
        lgbtq_protagonist: false,
        lgbtq_sidekick: false,
        lgbtq_theme: false,
        rating: 7
         }
]